Repository eojjeogo-jeojjeogo/issue-tracker-max, pull requests merged in 2023-08, with the labels that each got.

#27 #20 [BE] feat: 레이블 CRUD 기능 구현
  be/src/main/java/com/codesquad/issuetracker/IssueTrackerApplication.java
  be/src/main/java/com/codesquad/issuetracker/api/label/controller/LabelController.java
  be/src/main/java/com/codesquad/issuetracker/api/label/domain/Label.java
  be/src/main/java/com/codesquad/issuetracker/api/label/dto/LabelCreateRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/label/dto/LabelResponse.java
  be/src/main/java/com/codesquad/issuetracker/api/label/dto/LabelUpdateRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/label/repository/LabelRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/label/repository/LabelRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/label/service/LabelService.java
  be/src/main/java/com/codesquad/issuetracker/api/organization/repository/OrganizationRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/organization/repository/OrganizationRepositoryImpl.java
  be/src/main/resources/application-localDB.yml
  be/src/main/resources/application-prodDB.yml
  be/src/main/resources/application-testDB.yml
  be/src/test/java/com/codesquad/issuetracker/annotation/ControllerTest.java
  be/src/test/java/com/codesquad/issuetracker/annotation/RepositoryTest.java
  be/src/test/java/com/codesquad/issuetracker/annotation/ServiceTest.java
  be/src/test/resources/application-testDB.yml
  be/src/test/resources/application.yml
  be/src/test/resources/schema.sql
Labels: ☕️ BE, ✨ feature

#31 #30 [BE] feat: 마일스톤 아이디로 마일스톤 조회 기능 구현
  be/src/main/java/com/codesquad/issuetracker/api/milestone/controller/MilestoneController.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/domain/Milestone.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/dto/request/MilestoneCreateRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/dto/response/MileStoneResponse.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/repository/MilestoneRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/repository/MilestoneRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/service/MilestoneService.java
  be/src/test/java/com/codesquad/issuetracker/api/milestone/controller/MilestoneControllerTest.java
Labels: ☕️ BE, ✨ feature

#32 #22 [be] feat: 마일스톤 수정 기능 구현
  be/src/main/java/com/codesquad/issuetracker/api/milestone/controller/MilestoneController.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/dto/request/MilestoneCreateRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/dto/request/MilestoneRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/repository/MilestoneRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/repository/MilestoneRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/service/MilestoneService.java
  be/src/test/java/com/codesquad/issuetracker/api/milestone/controller/MilestoneControllerTest.java
  be/src/test/java/com/codesquad/issuetracker/api/milestone/repository/MilestoneRepositoryTest.java
Labels: ☕️ BE, ✨ feature

#37 #33 [be] feat:마일스톤 개별 삭제 기능
  be/src/main/java/com/codesquad/issuetracker/api/milestone/controller/MilestoneController.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/repository/MilestoneRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/repository/MilestoneRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/service/MilestoneService.java
  be/src/test/java/com/codesquad/issuetracker/api/milestone/controller/MilestoneControllerTest.java
  be/src/test/java/com/codesquad/issuetracker/api/milestone/repository/MilestoneRepositoryTest.java
Labels: ☕️ BE, ✨ feature

#38 #34 [be] feat: 마일스톤 전체 조회 기능
  be/src/main/java/com/codesquad/issuetracker/api/milestone/controller/MilestoneController.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/dto/response/MileStoneResponse.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/repository/MilestoneRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/repository/MilestoneRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/service/MileStonesResponse.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/service/MilestoneService.java
  be/src/test/java/com/codesquad/issuetracker/api/milestone/controller/MilestoneControllerTest.java
Labels: ☕️ BE, ✨ feature

#39 #35 [be] feat:마일스톤 상태 변경 기능
  be/src/main/java/com/codesquad/issuetracker/api/milestone/controller/MilestoneController.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/dto/request/MilestoneStatusRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/dto/response/MileStoneResponse.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/repository/MilestoneRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/repository/MilestoneRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/service/MilestoneService.java
  be/src/test/java/com/codesquad/issuetracker/api/milestone/controller/MilestoneControllerTest.java
Labels: ☕️ BE, ✨ feature

#41 #36 [be] feat: 마일스톤 필터 목록 조회 기능
  be/src/main/java/com/codesquad/issuetracker/api/filter/controller/FilterController.java
  be/src/main/java/com/codesquad/issuetracker/api/filter/dto/MilestoneFilter.java
  be/src/main/java/com/codesquad/issuetracker/api/filter/service/FilterService.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/controller/MilestoneController.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/dto/response/EditMileStoneResponse.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/dto/response/MilestoneResponse.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/dto/response/MilestonesResponse.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/repository/MilestoneRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/repository/MilestoneRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/service/MilestoneService.java
  be/src/test/java/com/codesquad/issuetracker/api/filter/controller/FilterControllerTest.java
  be/src/test/java/com/codesquad/issuetracker/api/milestone/controller/MilestoneControllerTest.java
Labels: ☕️ BE, ✨ feature

#47 #42 [be] feat: 레이블 필드 목록 조회 기능 구현
  be/src/main/java/com/codesquad/issuetracker/api/filter/controller/FilterController.java
  be/src/main/java/com/codesquad/issuetracker/api/filter/dto/LabelFilter.java
  be/src/main/java/com/codesquad/issuetracker/api/filter/service/FilterService.java
  be/src/main/java/com/codesquad/issuetracker/api/label/repository/LabelRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/label/repository/LabelRepositoryImpl.java
  be/src/test/java/com/codesquad/issuetracker/api/filter/controller/FilterControllerTest.java
Labels: ☕️ BE, ✨ feature

#40 #25 [be] feat: 이슈 코멘트 수정 기능
  be/src/main/java/com/codesquad/issuetracker/api/comment/controller/CommentController.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/dto/request/CommentRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/repository/CommentRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/repository/CommentRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/service/CommentService.java
  be/src/test/java/com/codesquad/issuetracker/api/comment/controller/CommentControllerTest.java
  be/src/test/resources/schemaForDummyData.sql
Labels: ☕️ BE, ✨ feature

#44 #43 [be] feat: 레이블 및 마이스톤 개수 조회 기능
  be/src/main/java/com/codesquad/issuetracker/api/common/controller/CommonController.java
  be/src/main/java/com/codesquad/issuetracker/api/common/dto/NavigationResponse.java
  be/src/main/java/com/codesquad/issuetracker/api/common/service/CommonService.java
  be/src/main/java/com/codesquad/issuetracker/api/label/repository/LabelRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/label/repository/LabelRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/repository/MilestoneRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/repository/MilestoneRepositoryImpl.java
  be/src/test/java/com/codesquad/issuetracker/api/common/controller/CommonControllerTest.java
  be/src/test/java/com/codesquad/issuetracker/api/milestone/acceptance/MilestoneAcceptanceTest.java
Labels: ☕️ BE, ✨ feature

#48 #28 [BE] 이슈 생성 기능
  be/src/main/java/com/codesquad/issuetracker/api/issue/controller/IssueController.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/domain/Issue.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/domain/IssueAssignee.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/domain/IssueLabel.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/dto/IssueCreateRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/repository/IssueRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/repository/IssueRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/service/IssueService.java
  be/src/test/java/com/codesquad/issuetracker/api/issue/controller/IssueControllerTest.java
Labels: ☕️ BE, ✨ feature

#50 [BE] CommentRequest로 dto가 변경되어 관련 코드 수정
  be/src/main/java/com/codesquad/issuetracker/api/issue/dto/IssueCreateRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/service/IssueService.java
Labels: ♻️ refactor, ☕️ BE

#54 [BE] cors 설정파일 추가
  be/src/main/java/com/codesquad/issuetracker/config/WebConfig.java
Labels: ☕️ BE, 🛠️ infra

#53 [BE] 이슈 삭제 기능 구현
  be/src/main/java/com/codesquad/issuetracker/api/issue/controller/IssueController.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/repository/IssueRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/repository/IssueRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/service/IssueService.java
Labels: ☕️ BE, ✨ feature

#62 [FE] 이슈페이지 및 컴포넌트 UI 구현
  fe/src/App.tsx
  fe/src/components/Header/Header.tsx
  fe/src/components/Issue/AddBox.tsx
  fe/src/components/Issue/AddBoxItem.tsx
  fe/src/components/Issue/Comment.tsx
  fe/src/components/Issue/Issue.tsx
  fe/src/components/Issue/IssueDropdownTab.tsx
  fe/src/components/Issue/IssueElement.tsx
  fe/src/components/Issue/IssueOption.tsx
  fe/src/components/Label/Label.tsx
  fe/src/components/Label/LabelDetail.tsx
  fe/src/components/Label/LabelElement.tsx
  fe/src/components/Milestone/MilestoneDetail.tsx
  fe/src/components/Milestone/MilestoneElement.tsx
  fe/src/components/common/Background.tsx
  fe/src/components/common/Dropdown.tsx
  fe/src/components/common/DropdownItem.tsx
  fe/src/components/common/FilterBar.tsx
  fe/src/components/common/Icon.tsx
  fe/src/components/common/TabButton.tsx
  fe/src/components/common/TextArea.tsx
  fe/src/components/common/TextInput.tsx
  fe/src/components/util/Alert.tsx
  fe/src/components/util/Txt.tsx
  fe/src/constants/colors.ts
  fe/src/constants/fonts.ts
  fe/src/constants/url.ts
  fe/src/contexts/AlertContext.tsx
  fe/src/contexts/IssueContext.tsx
  fe/src/contexts/LabelContext.tsx
  fe/src/hooks/useOutsideClick.tsx
  fe/src/pages/IssueDetailPage.tsx
  fe/src/pages/IssuePage.tsx
  fe/src/pages/LabelPage.tsx
  fe/src/pages/LoginPage.tsx
  fe/src/pages/MainPage.tsx
  fe/src/pages/MilestonePage.tsx
  fe/src/pages/NewIssuePage.tsx
  fe/src/pages/RegisterPage.tsx
  fe/src/styles/commonStyles.ts
Labels: 🐶 FE, ✨ feature

#63 refactor: 레이블 스타일 코드 색상오류 수정
  fe/src/components/Label/Label.tsx
Labels: 🐶 FE, ✨ feature

#58 [BE] 모든 이모티콘 목록을 불러오는 기능
  be/src/main/java/com/codesquad/issuetracker/api/comment/domain/Emoticon.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/repository/EmoticonRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/repository/EmoticonRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/repository/IssueRepositoryImpl.java
Labels: ☕️ BE, ✨ feature

#71 #45 [BE] 자동배포환경 구성
  .github/workflows/auto-deploy.yml
  be/Dockerfile
  docker-compose.yml
  fe/Dockerfile
  nginx/Dockerfile
  nginx/nginx.conf
Labels: ☕️ BE, 🛠️ infra

#76 #72 [BE] 이슈 수정 기능 구현
  be/src/main/java/com/codesquad/issuetracker/api/issue/controller/IssueController.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/domain/Issue.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/dto/IssueAssigneeUpdateRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/dto/IssueCreateRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/dto/IssueLabelUpdateRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/dto/IssueMilestoneUpdateRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/dto/IssueTitleUpdateRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/repository/IssueRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/repository/IssueRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/service/IssueService.java
Labels: ☕️ BE, ✨ feature

#77 #75 [be] 마일스톤 필터별 전체 목록 조회 기능 및 마일스톤 필터목록 조회 기능 수정
  be/src/main/java/com/codesquad/issuetracker/api/milestone/controller/MilestoneController.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/domain/Milestone.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/dto/response/MilestoneResponse.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/dto/response/MilestonesResponse.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/filterStatus/FilterStatus.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/repository/MilestoneRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/service/MilestoneService.java
Labels: ♻️ refactor, ☕️ BE

#80 #79 [BE] 이슈 상태 변경 기능 구현
  be/src/main/java/com/codesquad/issuetracker/api/issue/controller/IssueController.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/dto/IssueStatusUpdateRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/dto/IssuesStatusUpdateRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/repository/IssueRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/repository/IssueRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/service/IssueService.java
Labels: ☕️ BE, ✨ feature

#81 #26 [BE] feat: 코멘트 반응 추가기능 구현
  be/src/main/java/com/codesquad/issuetracker/api/comment/controller/CommentController.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/domain/Emoticon.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/dto/request/CommentEmoticonAddRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/repository/CommentEmoticonRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/repository/CommentEmoticonRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/service/CommentService.java
Labels: ☕️ BE, ✨ feature

#83 #82 [BE] refactor: 마일스톤 개별 및 전체조회 응답 수정
  be/src/main/java/com/codesquad/issuetracker/api/issue/repository/IssueRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/controller/MilestoneController.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/domain/MilestoneVo.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/domain/MilestonesVo.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/dto/response/EditMileStoneResponse.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/dto/response/MilestoneResponse.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/dto/response/MilestonesResponse.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/filterStatus/FilterStatus.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/repository/MilestoneRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/repository/MilestoneRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/service/MilestoneService.java
  be/src/test/java/com/codesquad/issuetracker/api/milestone/repository/MilestoneRepositoryTest.java
Labels: ♻️ refactor, ☕️ BE

#85 #55 [BE] 이슈 상세페이지 조회 기능 구현
  be/src/main/java/com/codesquad/issuetracker/api/comment/domain/Emoticon.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/repository/CommentRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/controller/IssueController.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/domain/IssueAssigneeVo.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/domain/IssueLabelVo.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/domain/IssueVo.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/dto/IssueResponse.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/repository/IssueAssigneeRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/repository/IssueAssigneeRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/repository/IssueLabelRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/repository/IssueLabelRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/repository/IssueRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/repository/IssueRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/service/IssueService.java
Labels: ☕️ BE, ✨ feature

#88 #84 [BE] 담당자 필터목록 조회기능 구현
  be/src/main/java/com/codesquad/issuetracker/api/filter/controller/FilterController.java
  be/src/main/java/com/codesquad/issuetracker/api/filter/dto/MemberFilter.java
  be/src/main/java/com/codesquad/issuetracker/api/filter/service/FilterService.java
  be/src/main/java/com/codesquad/issuetracker/api/member/repository/MemberRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/member/repository/MemberRepositoryImpl.java
Labels: ☕️ BE, ✨ feature

#90 #89 [BE] 리팩토링
  be/src/main/java/com/codesquad/issuetracker/api/comment/controller/CommentController.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/domain/CommentEmoticonVo.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/domain/Emoticon.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/domain/IssueCommentVo.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/dto/request/CommentEmoticonAddRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/dto/request/CommentRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/dto/response/CommentEmoticonResponse.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/dto/response/CommentResponse.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/repository/CommentEmoticonRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/repository/CommentEmoticonRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/repository/CommentRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/repository/CommentRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/repository/EmoticonRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/service/CommentService.java
  be/src/main/java/com/codesquad/issuetracker/api/common/controller/CommonController.java
  be/src/main/java/com/codesquad/issuetracker/api/common/service/CommonService.java
  be/src/main/java/com/codesquad/issuetracker/api/filter/controller/FilterController.java
  be/src/main/java/com/codesquad/issuetracker/api/filter/dto/LabelFilter.java
  be/src/main/java/com/codesquad/issuetracker/api/filter/dto/MemberFilter.java
  be/src/main/java/com/codesquad/issuetracker/api/filter/dto/MilestoneFilter.java
  be/src/main/java/com/codesquad/issuetracker/api/filter/service/FilterService.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/controller/IssueController.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/service/IssueService.java
  be/src/main/java/com/codesquad/issuetracker/api/label/controller/LabelController.java
  be/src/main/java/com/codesquad/issuetracker/api/label/domain/Label.java
  be/src/main/java/com/codesquad/issuetracker/api/label/dto/LabelCreateRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/label/dto/LabelUpdateRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/label/dto/request/LabelCreateRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/label/dto/request/LabelUpdateRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/label/dto/response/LabelResponse.java
  be/src/main/java/com/codesquad/issuetracker/api/label/repository/LabelRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/label/repository/LabelRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/label/service/LabelService.java
  be/src/main/java/com/codesquad/issuetracker/api/member/repository/MemberRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/member/repository/MemberRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/controller/MilestoneController.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/domain/Milestone.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/domain/MilestoneVo.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/domain/MilestonesVo.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/dto/request/MilestoneRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/dto/request/MilestoneStatusRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/repository/MilestoneRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/repository/MilestoneRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/service/MilestoneService.java
  be/src/main/java/com/codesquad/issuetracker/api/organization/repository/OrganizationRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/organization/repository/OrganizationRepositoryImpl.java
  be/src/test/java/com/codesquad/issuetracker/api/common/controller/CommonControllerTest.java
  be/src/test/java/com/codesquad/issuetracker/api/filter/controller/FilterControllerTest.java
  be/src/test/java/com/codesquad/issuetracker/api/milestone/repository/MilestoneRepositoryTest.java
Labels: ♻️ refactor, ☕️ BE

#94 #92 [BE] Webconfig에 ec2 주소 추가
  be/src/main/java/com/codesquad/issuetracker/config/WebConfig.java
Labels: ♻️ refactor, ☕️ BE, 🛠️ infra

#102 #1 [BE] 로그인 기능
  be/build.gradle
  be/src/main/java/com/codesquad/issuetracker/api/comment/controller/CommentController.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/domain/Comment.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/dto/request/CommentRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/repository/CommentRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/repository/CommentRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/service/CommentService.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/controller/IssueController.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/controller/IssueInfoController.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/domain/IssueVo.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/dto/IssueCreateRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/dto/IssueInfoResponse.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/dto/IssueResponse.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/repository/IssueAssigneeRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/repository/IssueAssigneeRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/repository/IssueLabelRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/repository/IssueLabelRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/repository/IssueRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/repository/IssueRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/service/IssueInfoService.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/service/IssueService.java
  be/src/main/java/com/codesquad/issuetracker/api/member/controller/MemberController.java
  be/src/main/java/com/codesquad/issuetracker/api/member/domain/Member.java
  be/src/main/java/com/codesquad/issuetracker/api/member/dto/request/RefreshTokenRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/member/dto/request/SignInRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/member/dto/request/SignUpRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/member/dto/response/SignInResponse.java
  be/src/main/java/com/codesquad/issuetracker/api/member/repository/MemberRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/member/repository/MemberRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/member/repository/TokenRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/member/repository/TokenRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/member/service/MemberService.java
  be/src/main/java/com/codesquad/issuetracker/api/oauth/OauthAttributes.java
  be/src/main/java/com/codesquad/issuetracker/api/oauth/config/InMemoryProviderRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/oauth/config/OauthAdapter.java
  be/src/main/java/com/codesquad/issuetracker/api/oauth/config/OauthConfig.java
  be/src/main/java/com/codesquad/issuetracker/api/oauth/config/OauthProperties.java
  be/src/main/java/com/codesquad/issuetracker/api/oauth/domain/OauthProvider.java
  be/src/main/java/com/codesquad/issuetracker/api/oauth/dto/request/OauthSignInRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/oauth/dto/response/OauthTokenResponse.java
  be/src/main/java/com/codesquad/issuetracker/api/oauth/dto/response/OauthUserProfile.java
  be/src/main/java/com/codesquad/issuetracker/api/oauth/service/OauthService.java
  be/src/main/java/com/codesquad/issuetracker/common/exception/GlobalExceptionHandler.java
  be/src/main/java/com/codesquad/issuetracker/common/exception/JwtExceptionResponse.java
  be/src/main/java/com/codesquad/issuetracker/common/exception/JwtExceptionType.java
  be/src/main/java/com/codesquad/issuetracker/common/filter/CorsFilter.java
  be/src/main/java/com/codesquad/issuetracker/common/filter/JwtFilter.java
  be/src/main/java/com/codesquad/issuetracker/config/FilterConfig.java
  be/src/main/java/com/codesquad/issuetracker/config/WebConfig.java
  be/src/main/java/com/codesquad/issuetracker/jwt/Jwt.java
  be/src/main/java/com/codesquad/issuetracker/jwt/JwtProvider.java
  be/src/main/resources/application-oauth.yml
  be/src/main/resources/application.yml
  be/src/main/resources/static/index.html
  be/src/test/java/com/codesquad/issuetracker/IssueTrackerApplicationTests.java
  be/src/test/resources/application.yml
Labels: ☕️ BE, ✨ feature

#108 #107 [BE] github redirect url 수정 및 리팩토링
  be/src/main/java/com/codesquad/issuetracker/common/exception/GlobalExceptionHandler.java
  be/src/main/resources/application-oauth.yml
  be/src/test/java/com/codesquad/issuetracker/api/comment/controller/CommentControllerTest.java
Labels: ☕️ BE

#115 #114 [BE] login response 수정
  be/src/main/java/com/codesquad/issuetracker/api/member/dto/request/SignInRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/member/dto/response/SignInResponse.java
  be/src/main/java/com/codesquad/issuetracker/api/member/repository/MemberRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/member/service/MemberService.java
  be/src/main/java/com/codesquad/issuetracker/common/filter/JwtFilter.java
Labels: ♻️ refactor, ☕️ BE

#113 #87 [BE] 이슈 필터링 조회 기능 구현
  be/build.gradle
  be/src/main/java/com/codesquad/issuetracker/api/issue/controller/IssueController.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/controller/IssueInfoController.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/domain/IssueFilterVo.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/dto/IssueFilterRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/dto/IssueFilterResponse.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/dto/IssueMilestoneUpdateRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/repository/IssueFilterMapper.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/repository/IssueFilterMapperImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/repository/IssueRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/repository/IssueRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/service/IssueService.java
  be/src/main/java/com/codesquad/issuetracker/api/member/dto/request/RefreshTokenRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/domain/Milestone.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/dto/response/MilestonesResponse.java
  be/src/main/java/com/codesquad/issuetracker/api/organization/repository/OrganizationRepositoryImpl.java
  be/src/main/resources/application-mybatis.yml
  be/src/main/resources/application-prodDB.yml
  be/src/main/resources/mybatis/IssueFilterMapper.xml
Labels: ☕️ BE, ✨ feature

#118 #116 [BE] 이슈필터링 기능 리팩토링
  be/src/main/java/com/codesquad/issuetracker/api/issue/dto/IssueFilterRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/service/IssueService.java
  be/src/main/resources/mybatis/IssueFilterMapper.xml
  be/src/test/java/com/codesquad/issuetracker/IssueTrackerApplicationTests.java
Labels: ♻️ refactor, ☕️ BE

#117 [BE] 파일 전송 기능 구현
  be/build.gradle
  be/src/main/java/com/codesquad/issuetracker/api/aws/AwsController.java
  be/src/main/java/com/codesquad/issuetracker/api/aws/S3Config.java
  be/src/main/java/com/codesquad/issuetracker/api/aws/S3Service.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/domain/Comment.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/domain/IssueCommentVo.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/dto/request/CommentRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/dto/response/CommentResponse.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/repository/CommentRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/service/IssueInfoService.java
  be/src/main/resources/application-aws.yml
  be/src/main/resources/application.yml
  be/src/test/java/com/codesquad/issuetracker/api/comment/controller/CommentControllerTest.java
  be/src/test/resources/application.yml
Labels: ☕️ BE, ✨ feature

#123 #119 [BE] 예외처리 구현
  be/build.gradle
  be/src/main/java/com/codesquad/issuetracker/api/comment/service/CommentService.java
  be/src/main/java/com/codesquad/issuetracker/api/common/service/CommonService.java
  be/src/main/java/com/codesquad/issuetracker/api/filter/service/FilterService.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/controller/IssueController.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/dto/IssueCreateRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/repository/IssueRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/repository/IssueRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/service/IssueService.java
  be/src/main/java/com/codesquad/issuetracker/api/jwt/domain/Jwt.java
  be/src/main/java/com/codesquad/issuetracker/api/jwt/repository/TokenRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/jwt/repository/TokenRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/jwt/service/JwtProvider.java
  be/src/main/java/com/codesquad/issuetracker/api/jwt/service/JwtService.java
  be/src/main/java/com/codesquad/issuetracker/api/label/controller/LabelController.java
  be/src/main/java/com/codesquad/issuetracker/api/label/dto/request/LabelCreateRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/label/dto/request/LabelUpdateRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/label/repository/LabelRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/label/repository/LabelRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/label/service/LabelService.java
  be/src/main/java/com/codesquad/issuetracker/api/member/controller/MemberController.java
  be/src/main/java/com/codesquad/issuetracker/api/member/dto/request/SignInRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/member/dto/request/SignUpRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/member/dto/response/SignInResponse.java
  be/src/main/java/com/codesquad/issuetracker/api/member/repository/MemberRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/member/repository/MemberRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/member/service/MemberService.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/controller/MilestoneController.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/dto/request/MilestoneRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/repository/MilestoneRepository.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/repository/MilestoneRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/service/MilestoneService.java
  be/src/main/java/com/codesquad/issuetracker/api/oauth/service/OauthService.java
  be/src/main/java/com/codesquad/issuetracker/api/organization/service/OrganizationService.java
  be/src/main/java/com/codesquad/issuetracker/common/exception/CustomRuntimeException.java
  be/src/main/java/com/codesquad/issuetracker/common/exception/JwtExceptionResponse.java
  be/src/main/java/com/codesquad/issuetracker/common/exception/JwtExceptionType.java
  be/src/main/java/com/codesquad/issuetracker/common/exception/customexception/CommentException.java
  be/src/main/java/com/codesquad/issuetracker/common/exception/customexception/CustomException.java
  be/src/main/java/com/codesquad/issuetracker/common/exception/customexception/IssueException.java
  be/src/main/java/com/codesquad/issuetracker/common/exception/customexception/JwtException.java
  be/src/main/java/com/codesquad/issuetracker/common/exception/customexception/LabelException.java
  be/src/main/java/com/codesquad/issuetracker/common/exception/customexception/MemberException.java
  be/src/main/java/com/codesquad/issuetracker/common/exception/customexception/MilestoneException.java
  be/src/main/java/com/codesquad/issuetracker/common/exception/customexception/OauthException.java
  be/src/main/java/com/codesquad/issuetracker/common/exception/customexception/OrganizationException.java
  be/src/main/java/com/codesquad/issuetracker/common/exception/customexception/SignInException.java
  be/src/main/java/com/codesquad/issuetracker/common/exception/customexception/SignUpException.java
  be/src/main/java/com/codesquad/issuetracker/common/exception/handler/GlobalExceptionHandler.java
  be/src/main/java/com/codesquad/issuetracker/common/filter/JwtFilter.java
Labels: ☕️ BE, ✨ feature

#124 #105 [BE] 메인페이지 정적 필터 조회 기능
  be/src/main/java/com/codesquad/issuetracker/api/comment/dto/request/CommentRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/comment/repository/CommentRepositoryImpl.java
  be/src/main/java/com/codesquad/issuetracker/api/filter/controller/FilterController.java
  be/src/main/java/com/codesquad/issuetracker/api/filter/dto/StaticFiltersResponse.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/dto/IssueCreateRequest.java
Labels: ☕️ BE, ✨ feature

#126 #125 [BE] 로그아웃 기능 구현
  be/build.gradle
  be/src/main/java/com/codesquad/issuetracker/api/comment/controller/CommentController.java
  be/src/main/java/com/codesquad/issuetracker/api/filter/controller/FilterController.java
  be/src/main/java/com/codesquad/issuetracker/api/issue/controller/IssueController.java
  be/src/main/java/com/codesquad/issuetracker/api/jwt/service/JwtService.java
  be/src/main/java/com/codesquad/issuetracker/api/member/controller/MemberController.java
  be/src/main/java/com/codesquad/issuetracker/api/member/service/MemberService.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/controller/MilestoneController.java
  be/src/main/java/com/codesquad/issuetracker/api/milestone/service/MilestoneService.java
  be/src/main/java/com/codesquad/issuetracker/common/exception/customexception/JwtException.java
  be/src/main/java/com/codesquad/issuetracker/common/filter/JwtFilter.java
  be/src/main/java/com/codesquad/issuetracker/common/util/RequestUtil.java
  be/src/main/java/com/codesquad/issuetracker/redis/RedisProperties.java
  be/src/main/java/com/codesquad/issuetracker/redis/config/RedisConfig.java
  be/src/main/java/com/codesquad/issuetracker/redis/util/RedisUtil.java
  be/src/main/resources/application-redis.yml
  be/src/main/resources/application.yml
Labels: ☕️ BE, ✨ feature

#128 [FE] 자동배포환경 구성을 위한 pr
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/components/Header/Header.tsx
  fe/src/components/Issue/AddBox.tsx
  fe/src/components/Issue/AddBoxItem.tsx
  fe/src/components/Issue/Comment.tsx
  fe/src/components/Issue/IssueDropdownTab.tsx
  fe/src/components/Issue/IssueElement.tsx
  fe/src/components/Issue/IssueOption.tsx
  fe/src/components/Label/LabelDetail.tsx
  fe/src/components/Milestone/MilestoneDetail.tsx
  fe/src/components/Milestone/MilestoneElement.tsx
  fe/src/components/common/Dropdown.tsx
  fe/src/components/common/FilterBar.tsx
  fe/src/components/common/TextArea.tsx
  fe/src/components/common/TextInput.tsx
  fe/src/components/util/Alert.tsx
  fe/src/constants/url.ts
  fe/src/contexts/IssueContext.tsx
  fe/src/contexts/TokenContext.tsx
  fe/src/hooks/useTheme.tsx
  fe/src/pages/Auth.tsx
  fe/src/pages/IssueDetailPage.tsx
  fe/src/pages/IssuePage.tsx
  fe/src/pages/LabelPage.tsx
  fe/src/pages/LoginPage.tsx
  fe/src/pages/MilestonePage.tsx
  fe/src/pages/NewIssuePage.tsx
  fe/src/pages/ProfilePage.tsx
  fe/src/pages/RegisterPage.tsx
  fe/src/styles/commonStyles.ts
Labels: 🐶 FE

#130 #127 [BE] 테스트 코드 작성
  be/src/main/java/com/codesquad/issuetracker/api/comment/dto/request/CommentEmoticonAddRequest.java
  be/src/main/java/com/codesquad/issuetracker/api/member/dto/request/SignUpRequest.java
  be/src/test/java/com/codesquad/issuetracker/annotation/ControllerTest.java
  be/src/test/java/com/codesquad/issuetracker/api/comment/controller/CommentControllerTest.java
  be/src/test/java/com/codesquad/issuetracker/api/common/controller/CommonControllerTest.java
  be/src/test/java/com/codesquad/issuetracker/api/filter/controller/FilterControllerTest.java
  be/src/test/java/com/codesquad/issuetracker/api/milestone/controller/MilestoneControllerTest.java
  be/src/test/java/com/codesquad/issuetracker/init/BaseControllerTest.java
  be/src/test/resources/application-testDB.yml
  be/src/test/resources/application.yml
  be/src/test/resources/schema.sql
  be/src/test/resources/schemaForDummyData.sql
Labels: ☕️ BE, 🚦test
