Repository eojjeogo-jeojjeogo/issue-tracker-max, pull requests merged in 2023-07, with the labels that each got.

#7 #3 [FE] 로그인/회원가입 기능 구현
  fe/.prettierrc
  fe/src/App.tsx
  fe/src/assets/LogotypeLarge.svg
  fe/src/assets/LogotypeMedium.svg
  fe/src/assets/ProfileImage.png
  fe/src/components/Header/Header.tsx
  fe/src/components/Issue/Issue.tsx
  fe/src/components/common/Background.tsx
  fe/src/components/common/Button.tsx
  fe/src/components/common/TextInput.tsx
  fe/src/components/util/Txt.tsx
  fe/src/index.css
  fe/src/pages/LoginPage.tsx
  fe/src/pages/MainPage.tsx
  fe/src/pages/RegisterPage.tsx
Labels: 🐶 FE, ✨ feature

#11 #10 [BE] 프로젝트 초기 세팅
  be/.gitignore
  be/build.gradle
  be/gradle/wrapper/gradle-wrapper.jar
  be/gradle/wrapper/gradle-wrapper.properties
  be/gradlew
  be/gradlew.bat
  be/settings.gradle
  be/src/main/java/com/codesquad/issuetracker/IssueTrackerApplication.java
  be/src/main/resources/application-jasypt.yml
  be/src/main/resources/application-localDB.yml
  be/src/main/resources/application-prodDB.yml
  be/src/main/resources/application-testDB.yml
  be/src/main/resources/application.yml
  be/src/test/java/com/codesquad/issuetracker/IssueTrackerApplicationTests.java
Labels: ☕️ BE, 🔧chore

#13 #8 [FE] 레이블 페이지 UI 및 기능 구현
  fe/src/App.tsx
  fe/src/assets/Icons/alertCircle.svg
  fe/src/assets/Icons/archive.svg
  fe/src/assets/Icons/calendar.svg
  fe/src/assets/Icons/checkBoxActive.svg
  fe/src/assets/Icons/checkBoxDisable.svg
  fe/src/assets/Icons/checkBoxInitial.svg
  fe/src/assets/Icons/checkOffCircle.svg
  fe/src/assets/Icons/checkOnCircle.svg
  fe/src/assets/Icons/chevronDown.svg
  fe/src/assets/Icons/darkTheme.svg
  fe/src/assets/Icons/edit.svg
  fe/src/assets/Icons/label.svg
  fe/src/assets/Icons/milestone.svg
  fe/src/assets/Icons/paperclip.svg
  fe/src/assets/Icons/plus.svg
  fe/src/assets/Icons/refreshCcw.svg
  fe/src/assets/Icons/search.svg
  fe/src/assets/Icons/smile.svg
  fe/src/assets/Icons/trash.svg
  fe/src/assets/Icons/userImageLarge.svg
  fe/src/assets/Icons/userImageSmall.svg
  fe/src/assets/Icons/xSquare.svg
  fe/src/components/Header/Header.tsx
  fe/src/components/Label/ColorSelector.tsx
  fe/src/components/Label/Label.tsx
  fe/src/components/Label/LabelDetail.tsx
  fe/src/components/Label/LabelElement.tsx
  fe/src/components/common/Background.tsx
  fe/src/components/common/Button.tsx
  fe/src/components/common/DarkModeButton.tsx
  fe/src/components/common/DetailTextInput.tsx
  fe/src/components/common/Dropdown.tsx
  fe/src/components/common/DropdownItem.tsx
  fe/src/components/common/Icon.tsx
  fe/src/components/common/TabButton.tsx
  fe/src/components/common/TextInput.tsx
  fe/src/components/util/Alert.tsx
  fe/src/components/util/Txt.tsx
  fe/src/constants/colors.ts
  fe/src/contexts/LabelContext.tsx
  fe/src/contexts/ThemeContext.tsx
  fe/src/hooks/useTheme.tsx
  fe/src/index.css
  fe/src/pages/LabelPage.tsx
  fe/src/pages/LoginPage.tsx
  fe/src/pages/MilestonePage.tsx
  fe/src/pages/RegisterPage.tsx
Labels: 🐶 FE, ✨ feature, 🔧chore

#14 merge: [FE] 공통 컴포넌트,스타일 생성 및 CSS 수정
  fe/src/components/Header/Header.tsx
  fe/src/components/Label/ColorSelector.tsx
  fe/src/components/Label/Label.tsx
  fe/src/components/Label/LabelDetail.tsx
  fe/src/components/Label/LabelElement.tsx
  fe/src/components/common/Background.tsx
  fe/src/components/common/Button.tsx
  fe/src/components/common/DetailTextInput.tsx
  fe/src/components/common/Dropdown.tsx
  fe/src/components/common/DropdownItem.tsx
  fe/src/components/common/Icon.tsx
  fe/src/components/common/MainArea.tsx
  fe/src/components/common/TabButton.tsx
  fe/src/components/common/TextInput.tsx
  fe/src/components/util/Alert.tsx
  fe/src/components/util/Txt.tsx
  fe/src/constants/fonts.ts
  fe/src/pages/LabelPage.tsx
  fe/src/pages/LoginPage.tsx
  fe/src/pages/MilestonePage.tsx
  fe/src/pages/RegisterPage.tsx
  fe/src/styles/commonStyles.ts
Labels: 🐶 FE, 🔧chore

#17 #15 [FE] 마일스톤 페이지 생성,편집 기능 구현
  fe/src/components/Milestone/MilestoneDetail.tsx
  fe/src/components/Milestone/MilestoneElement.tsx
  fe/src/pages/MilestonePage.tsx
Labels: 🐶 FE, ✨ feature

#18 [FE] 다크모드 애니메이션 및 로고 변경
  fe/src/assets/Icons/moon.svg
  fe/src/assets/Icons/sun.svg
  fe/src/components/common/DarkModeButton.tsx
Labels: 🐶 FE, ♻️ refactor

#19 [FE] 스타일 코드 컴포넌트 외부로 분리
  fe/src/components/Label/ColorSelector.tsx
  fe/src/components/Label/Label.tsx
  fe/src/components/common/Background.tsx
  fe/src/components/common/Button.tsx
  fe/src/components/common/DetailTextInput.tsx
  fe/src/components/common/MainArea.tsx
  fe/src/components/common/TextInput.tsx
  fe/src/styles/commonStyles.ts
Labels: 🐶 FE, ♻️ refactor, 🎨 style
